// vue-todos/src/App.vue
<template>
  <div>
    <h1>Hello world!</h1>
    <ul>
      <li v-for="todo in todos" :key="todo.id">
        <span :class="{ completed : todo.done }">{{todo.text}}</span>
        <button @click="removeTodo(todo.id)">x</button>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "App",

  data() {
    return {
      todos: [
        { id: 1, text: "Learn Angular", done: true },
        { id: 2, text: "Seek for a job", done: false },
        { id: 3, text: "Forget everything" }
      ]
    };
  },

  methods: {
    removeTodo(id) {
      const index = this.todos.findIndex(todo => todo.id === id);
      this.todos.splice(index, 1);
    }
  }
};
</script>

<style scoped>
.completed {
  text-decoration: line-through;
}
</style>

// angular-todos/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  todos = [
    { id: 1, text: 'Learn Angular', done: true },
    { id: 2, text: 'Seek for a job', done: false },
    { id: 3, text: 'Forget everything' }
  ];

  removeTodo(id) {
    const index = this.todos.findIndex(todo => todo.id === id);
    this.todos.splice(index, 1);
  }
}

<h1>Hello world!</h1>

<ul>
  <li *ngFor="let todo of todos">
    <span [ngClass]="{ completed: todo.done }">{{ todo.text }}</span>
    <button (click)="removeTodo(todo.id)">x</button>
  </li>
</ul>
